### ISSUE TITLE
Server crashed: NetworkBinaryStream::putSignedBlockPosition()

### ISSUE THREAD

**Issue by dadodasyra** [Benedikt05/BetterAltay#126]
Link to crashdump:  https://pastebin.com/FzUsPZeE

### Additional comments (optional)
I don't have any idea how it's produced. Yeah the file name of the server is "EskoBE" but it's BetterAltay renamed because I dont want to rename the file in the start.sh

**Comment by dadodasyra** [comment]
@Benedikt05 So it's caused by maps. When creating a map it crash

**Comment by dadodasyra** [comment]
The pastebin has been banned by pastebin without any reason, so here is a hastebin https://hastebin.com/fijelosepu.apache

**Comment by Benedikt05** [comment]
> @Benedikt05 So it's caused by maps. When creating a map it crash

Should be fixed in 1.7.1
