### ISSUE TITLE
fly and fall damage

### ISSUE THREAD

**Issue by efor89** [Benedikt05/BetterAltay#130]
if allowFly is true the player dont become falldamage!

### Steps to reproduce the issue
1. make /fly command
2. use /fly
3. toggle fly with hit space on windows in the air 
4. fall on ground

**Comment by Benedikt05** [comment]
ill try it out

**Comment by JoseLuisHD** [comment]
@efor89 Does everything work correctly?

**Comment by efor89** [comment]
yes now all work correct thx :)
