### ISSUE TITLE
add the item and block code of pmmp api4

### ISSUE THREAD

**Issue by efor89** [Benedikt05/BetterAltay#135]
## Description
Add the block and item code of pmmp api4 that we can add all blocks without extendedblocks.
Or some other code wat can do this.
Or remove the limit 0-255 for blocks and the limit for items that all ids can be a block or an item.
Or add the block limit to -2000 - 255.

## Justification
After this the negative ids are real blocks and Ba is the best server softwere for mcpe.

**Comment by efor89** [comment]
i found this so i think its possible
https://github.com/Benedikt05/BetterAltay/blob/master/tests/phpunit/block/BlockTest.php#L79

**Comment by MonoAdrian23** [comment]
PowernukkitX is the best Server Software for MCBE.
Betteraltay lacks a Lot of Features and is Feature outdated.
At next, PM5 is comming.

PowernukkitX haves all Minecraft BE Features and fully Vanilla Experience.

**Comment by efor89** [comment]
i set this in the blockfactory.php 

self::$fullList = new SplFixedArray(4096);

self::$light = new SplFixedArray(256);
self::$lightFilter = new SplFixedArray(256);
self::$solid = new SplFixedArray(256);
self::$hardness = new SplFixedArray(256);
self::$transparent = new SplFixedArray(256);
self::$diffusesSkyLight = new SplFixedArray(256);
self::$blastResistance = new SplFixedArray(256);

to

self::$fullList = new SplFixedArray(65536);

self::$light = new SplFixedArray(4096);
self::$lightFilter = new SplFixedArray(4096);
self::$solid = new SplFixedArray(4096);
self::$hardness = new SplFixedArray(4096);
self::$transparent = new SplFixedArray(4096);
self::$diffusesSkyLight = new SplFixedArray(4096);
self::$blastResistance = new SplFixedArray(4096);

with this its posibile to register blocks with id over 255 i can give me the item and its in creative inv.
only place its not working the block is showing as update block first  but on klick its one of the 0-255 blocks
i try it with id 1326 the place block was tnt

**Comment by efor89** [comment]
what in the code handle that the correct block is set?

**Comment by efor89** [comment]
i look in a lot of files like anvil.php pmanvil.php and all wat for level is but i find nothing.

**Comment by vp817** [comment]
do a change in runtimeblockmapping and it will work

**Comment by efor89** [comment]
can you help me plz i rly dont know how or what i have to change.

**Comment by vp817** [comment]
https://github.com/Benedikt05/BetterAltay/blob/master/src/pocketmine/network/mcpe/convert/RuntimeBlockMapping.php#L67#121

u need to change and remove and add some things i forgot inside

**Comment by vp817** [comment]
https://github.com/VaxPex/NetheriteBlock

onEnable inside it there is the code

**Comment by efor89** [comment]
i try a lot of change in this but nothing was working ^^

**Comment by vp817** [comment]
copy esko one and it will work

**Comment by efor89** [comment]
no its not working

**Comment by Benedikt05** [comment]
> copy esko one and it will work

Esko uses ExtendedBlocks plugin

**Comment by vp817** [comment]
> no its not working

use esko Runtimeblockmapping and eskopluyon anf it woill work

**Comment by efor89** [comment]
wat is eskopluyon?
but i locking for a way to set blocks as block not as tile!
