### ISSUE TITLE
NPC

### ISSUE THREAD

**Issue by Zinkaio** [Benedikt05/BetterAltay#138]
Impossible to add skins to NPCs and NPCs updated movements don't update as it should, for example making it rotate/spin.

**Comment by efor89** [comment]
i use slapper and slapperrotation and it works perfekt.

**Comment by Zinkaio** [comment]
which one: Send me a link to it

**Comment by efor89** [comment]
https://github.com/jojoe77777/Slapper
all you have to do is remove this line in the plugin.yml
mcpe-protocol: [361, 388, 389, 390, 407, 408]

**Comment by Zinkaio** [comment]
The slapper does work, my issue is my own plugin

$nbt->setTag(new CompoundTag('Skin', [
			new StringTag('Name', $skindata->getSkinId()),
			new ByteArrayTag('Data', $skindata->getSkinData()),
			new ByteArrayTag('CapeData', $skindata->getCapeData()),
			new StringTag('GeometryName', $skindata->getGeometryName()),
			new ByteArrayTag('GeometryData', $skindata->getGeometryData())
		]));
		
		Server::getInstance()->getDefaultLevel()->loadChunk($x >> 4, $z >> 4);
		
		$entity = Entity::createEntity("NPCEntity", Server::getInstance()->getDefaultLevel(), clone $nbt);
		
		$skindata->setVerified(true);
		$entity->setSkin($skindata);
		$entity->sendSkin(Server::getInstance()->getOnlinePlayers());
		
		that doesnt work, which used to

**Comment by Zinkaio** [comment]
NPCs do spawn and all, but they are stuck with Steve skins

**Comment by Benedikt05** [comment]
> NPCs do spawn and all, but they are stuck with Steve skins

Make sure you have disabled "Only Allowed Trusted Skins" in your Minecraft settings

**Comment by Zinkaio** [comment]
Nah I fix it, and I have that disable btw

It would seem that somwhere the sendSkin() isn’t updating, SO I had to
manually update it and now it works fine
