### ISSUE TITLE
api for set biom temperature

### ISSUE THREAD

**Issue by efor89** [Benedikt05/BetterAltay#140]
## Description
hi can you add an api that we can change the biom temperature in a chunk?
or that we can change rain to snow without change the biomeid?

getChunk()->setBiomeTemperature()

or something else to change the rain to snow

## Justification
in the moment i can only make that its snowing with getChunk()->setBiomId(12).
but with this you can not set the biomid back to the normal biomid.
there are to manny bioms in one world to set it back to normal biomid.
so with temp i think we can let it snow without change the biomid.
or some networkpacket can handle this idk.
start rain is easy but for start snow it give nothing?

**Comment by efor89** [comment]
?

**Comment by CulteredSaint** [comment]
get the biome of the chunk then change it to what u want then reset it

**Comment by efor89** [comment]
and i think you dont read wat i have written

**Comment by CulteredSaint** [comment]
> no @CulteredSaint thats not working if you do it like this you have to save all biom ids from all chunks in 1 file that you can give every chunk the correct biom id back.

wrong u save the biome id in an array then u change it again if u want and when the plugin disables it gets all modified chunks and reset their biomeid

**Comment by efor89** [comment]
i want that it snow in every chunk i need it for a weather plugin.
but if i walk in my worlds with so manny bioms i cant save all the biom ids and set it back to normal biomid
its super easy to start rain in all worlds but start snow in the worlds is not working only if the biom have id 12
and if i change all the biom ids in all chunks how can i set the chunks back to normal ids like 1, 2, 3, 4 and so on

**Comment by CulteredSaint** [comment]
just save them in db

**Comment by CulteredSaint** [comment]
its not like u will be able to open the db
