### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by angga7togk** [Benedikt05/BetterAltay#157]
please fix the stuck bug when entering nether and end

**Comment by Benedikt05** [comment]
i cant reproduce this bug

**Comment by angga7togk** [comment]
okay, it's okay, the important thing is that the Better Altay software is updated, and it's really good to be able to use the PM3 plugin

**Comment by Benedikt05** [comment]
have you tried it without plugins?

**Comment by vp817** [comment]
the crash is probably client crashing not some server crash

**Comment by Benedikt05** [comment]
> 

@angga7togk

**Comment by angga7togk** [comment]
I have fixed Nether myself using a plugin :), thanks for responding :), And keep on updating the software :), really cool :)
