### ISSUE TITLE
Invalid Player List Info

### ISSUE THREAD

**Issue by angga7togk** [Benedikt05/BetterAltay#163]
please fix the bug, when entering the server a message appears, "invalid player list info"

**Comment by angga7togk** [comment]
1.9.0

**Comment by CulteredSaint** [comment]
then use 1.10 u idiot

**Comment by CulteredSaint** [comment]
this is caused cuz u use mc ver: 1.19.62 on betteraltay ver: 1.9 and the 1.9 ver only supports 1.19.60 and there is no protocol dump for mc 1.19.62 so its the same protocol as 1.19.60 but with skin protocol changes
