### ISSUE TITLE
Glow SignText

### ISSUE THREAD

**Issue by efor89** [Benedikt05/BetterAltay#170]
## Description
hi
can you plz add that we can add glow sign text (not with glow_inc_sak only in code)?
its in pmmp5 alredy impliment
https://github.com/pmmp/PocketMine-MP/blob/5.0.0-BETA2/src/block/tile/Sign.php 

## Justification
after the editor was add, the signtext is rly dark and with this we can make it glow.
and its rly cool if ba have it.

**Comment by Jossuy** [comment]
Sure

**Comment by efor89** [comment]
ty :)

**Comment by efor89** [comment]
can u add plz signColorChangeEvent?
that we can chancel it for some plugins plz?

**Comment by JoseLuisHD** [comment]
https://github.com/Benedikt05/BetterAltay/commit/02bb5f7366fb95a34854602e6b621d75b7bb9b07

**Comment by efor89** [comment]
why close?

**Comment by efor89** [comment]
without this changes i works axactly same

**Comment by vp817** [comment]
> without this changes it works axactly same

didnt josi or something add signcolorchangeevent or something?

**Comment by efor89** [comment]
yes but if u remove all the code with color and glow from ba it change nothing.
if u klick on sign with dye the color change only for you and after rejoin the color is gone.
with glow its change to glow if you open editormode with glowincsac and after close editor glow is gone.

**Comment by efor89** [comment]
so in the moment the event do nothing.
