### ISSUE TITLE
nether generator

### ISSUE THREAD

**Issue by efor89** [Benedikt05/BetterAltay#179]
### Issue description

hi
the nether generator only generate bedrock netherrack and lava.

### Steps to reproduce the issue
1. create nether true in altay.yml
2. go to nether

### OS and versions
* BetterAltay: 1.13
* PHP: 8
* Game version: all

### Plugins
non

**Comment by FurkanYks** [comment]
what u want from nether?

**Comment by efor89** [comment]
and magma and fire if u can do it

**Comment by vp817** [comment]
doing it is ez but who will do it?

**Comment by efor89** [comment]
glowstone soulsand netherwart are alredy in the code but the generator dont generate this blocks anymore

**Comment by vp817** [comment]
ok i will take a look
