### ISSUE TITLE
stone slab

### ISSUE THREAD

**Issue by efor89** [Benedikt05/BetterAltay#181]
### Issue description

hi
i try to craft normal stone slab but i can't.
if i put stone block in crafting table it always give me smothe stone slab as output.

### Steps to reproduce the issue
1. put stone block in craftingtable and try make slab

### OS and versions

* Altay: 1.13.1
* PHP: 8
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins
no other plugin

**Comment by Benedikt05** [comment]
I couldn't reproduce that
