### ISSUE TITLE
blacklist plugin

### ISSUE THREAD

**Issue by keenanyafiqy** [Benedikt05/BetterAltay#20]
i want it have an blacklist plugin where if you type a specific plugin that you have in blacklist, it will disable the plugin and not loaded.

like in pmmp

**Comment by VaxPex** [comment]
Pm4 is trash and ok i will add that thing

**Comment by keenanyafiqy** [comment]
uhm..
wdym?

the changes that made me mad from pm4 is region world become db

**Comment by VaxPex** [comment]
> uhm.. wdym?
> 
> the changes that made me mad from pm4 is region world become db

The pmanvil can be turned into anvil then put it in worlds and tp to it then it will be leveldb

**Comment by keenanyafiqy** [comment]
does it need ChunkUtils?

**Comment by VaxPex** [comment]
No

**Comment by VaxPex** [comment]
I dont help ppl in pm4 cuz its trash

**Comment by Benedikt05** [comment]
> I dont help ppl in pm4 cuz its trash

Pm4 isn"t trash. Most (not all) chages are good.

**Comment by VaxPex** [comment]
pm4 still trash u did not see all the bugs

**Comment by keenanyafiqy** [comment]
so maybe in 1 march, get a new api.

**Comment by keenanyafiqy** [comment]
wait what

**Comment by Benedikt05** [comment]
> No one cares api 4 trash + new bugs added

I accept your opinion but please don't tell everyone that Pm4 is trash!

**Comment by VaxPex** [comment]
No api4 trash u are like pm4 if defend it

**Comment by VaxPex** [comment]
If u like pm4 and u say its not trash why u dont stop the betteraltay and go to pm4?
pm4 for losers

**Comment by Benedikt05** [comment]
> If u like pm4 and u say its not trash why u dont stop the betteraltay and go to pm4? pm4 for losers

I never said that I won't switch to Pm4!

**Comment by VaxPex** [comment]
> > If u like pm4 and u say its not trash why u dont stop the betteraltay and go to pm4? pm4 for losers
> 
> I never said that I won't switch to Pm4!

It means u will be goat like the goats in pm4

**Comment by keenanyafiqy** [comment]
okay then
i found a better software. goodbye

**Comment by VaxPex** [comment]
ok pm4 lover
