### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by Kingom1** [Benedikt05/BetterAltay#203]
![Screenshot_٢٠٢٣٠٧٢٠-١٥٣٠٢٠](https://github.com/Benedikt05/BetterAltay/assets/102631520/c15969e0-bdeb-4209-ae58-a5f75e50dd65)

Link to crashdump:

**Comment by mohamadOC** [comment]
World is null it means the world is unloaded you must have a look at your plugin and load the world first and i recommend to load all worlds  in the onEnable function

**Comment by Kingom1** [comment]
> 

No

**Comment by vp817** [comment]
yes load the world and it will be fixed

**Comment by Kingom1** [comment]
Hey, when I work as a tp for the world, there is no problem in the world, I understand
