### ISSUE TITLE
starting the server from source code

### ISSUE THREAD

**Issue by Deflan7** [Benedikt05/BetterAltay#23]
Good afternoon, how do I start the server from the source code? I want to make changes to the kernel myself. I didn't work with the composer. What do I need to do to update the dependencies and create a vendor, or whatever?

I started compouser and got the following response:

"Your requirements could not be resolved to an installable set of packages."

**Comment by Deflan7** [comment]
I started compouser and got the following response:

"Your requirements could not be resolved to an installable set of packages."

**Comment by keenanyafiqy** [comment]
Try to download the BetterAltay.phar and start.sh/start.cmd from the releases and source code files
Don't forget for the bin folder that was filled with php files

Then run start.sh/start.cmd

NOTE (If you didn't know):
start.sh can only be executed by bash command in Linux
start.cmd can be executed by opening the files in Windows

**Comment by Deflan7** [comment]
The problem is that I need to run src.

**Comment by keenanyafiqy** [comment]
for what?

**Comment by Benedikt05** [comment]
https://github.com/Benedikt05/BetterAltay/blob/master/BUILDING.md
(Replace https://github.com/pmmp/PocketMine-MP.git with https://github.com/Benedikt05/BetterAltay.git)

**Comment by Deflan7** [comment]
no work :(

**Comment by Deflan7** [comment]
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-chunkutils2 ^0.3.1 is missing from your system. Install or enable PHP's chunkutils2 extension.
  Problem 2
    - The requested PHP extension ext-crypto ^0.3.1 is missing from your system. Install or enable PHP's crypto extension.
  Problem 3
    - The requested PHP extension ext-gmp * is missing from your system. Install or enable PHP's gmp extension.
  Problem 4
    - The requested PHP extension ext-igbinary ^3.0.1 is missing from your system. Install or enable PHP's igbinary extension.
  Problem 5
    - The requested PHP extension ext-leveldb ^0.2.1 || ^0.3.0 is missing from your system. Install or enable PHP's leveldb extension.
  Problem 6
    - The requested PHP extension ext-morton ^0.1.0 is missing from your system. Install or enable PHP's morton extension.
  Problem 7
    - The requested PHP extension ext-pthreads ^4.0 is missing from your system. Install or enable PHP's pthreads extension.
  Problem 8
    - The requested PHP extension ext-yaml >=2.0.0 is missing from your system. Install or enable PHP's yaml extension.
  Problem 9
    - The requested package composer-runtime-api could not be found in any version, there may be a typo in the package name.
  Problem 10
    - Installation request for pocketmine/classloader 0.2.0 -> satisfiable by pocketmine/classloader[0.2.0].
    - pocketmine/classloader 0.2.0 requires ext-pthreads ~3.2.0 || ^4.0 -> the requested PHP extension pthreads is missing from your system.
  Problem 11
    - Installation request for pocketmine/log-pthreads 0.4.0 -> satisfiable by pocketmine/log-pthreads[0.4.0].
    - pocketmine/log-pthreads 0.4.0 requires ext-pthreads ~3.2.0 || ^4.0 -> the requested PHP extension pthreads is missing from your system.
  Problem 12
    - Installation request for pocketmine/snooze 0.3.1 -> satisfiable by pocketmine/snooze[0.3.1].
    - pocketmine/snooze 0.3.1 requires ext-pthreads ~3.2.0 || ^4.0 -> the requested PHP extension pthreads is missing from your system.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.4/cli/php.ini
    - /etc/php/7.4/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.4/cli/conf.d/10-opcache.ini
    - /etc/php/7.4/cli/conf.d/10-pdo.ini
    - /etc/php/7.4/cli/conf.d/15-xml.ini
    - /etc/php/7.4/cli/conf.d/20-bz2.ini
    - /etc/php/7.4/cli/conf.d/20-calendar.ini
    - /etc/php/7.4/cli/conf.d/20-ctype.ini
    - /etc/php/7.4/cli/conf.d/20-curl.ini
    - /etc/php/7.4/cli/conf.d/20-dom.ini
    - /etc/php/7.4/cli/conf.d/20-exif.ini
    - /etc/php/7.4/cli/conf.d/20-ffi.ini
    - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.4/cli/conf.d/20-ftp.ini
    - /etc/php/7.4/cli/conf.d/20-gd.ini
    - /etc/php/7.4/cli/conf.d/20-gettext.ini
    - /etc/php/7.4/cli/conf.d/20-iconv.ini
    - /etc/php/7.4/cli/conf.d/20-json.ini
    - /etc/php/7.4/cli/conf.d/20-mbstring.ini
    - /etc/php/7.4/cli/conf.d/20-mysqli.ini
    - /etc/php/7.4/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.4/cli/conf.d/20-phar.ini
    - /etc/php/7.4/cli/conf.d/20-posix.ini
    - /etc/php/7.4/cli/conf.d/20-readline.ini
    - /etc/php/7.4/cli/conf.d/20-shmop.ini
    - /etc/php/7.4/cli/conf.d/20-simplexml.ini
    - /etc/php/7.4/cli/conf.d/20-sockets.ini
    - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.4/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.4/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.4/cli/conf.d/20-xsl.ini
    - /etc/php/7.4/cli/conf.d/20-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by Benedikt05** [comment]
It does. What error do you get?

**Comment by Deflan7** [comment]
I've tried with different forks and even the official pmmp repository

**Comment by VaxPex** [comment]
@Deflan7 you need to put it somewhere in the pc

**Comment by VaxPex** [comment]
https://youtu.be/95yyhwgrrIs
Look at 1:06

**Comment by Deflan7** [comment]
Your requirements could not be resolved to an installable set of packages.

**Comment by keenanyafiqy** [comment]
try doing an composer update?
