### ISSUE TITLE
i may need api4🙃

### ISSUE THREAD

**Issue by keenanyafiqy** [Benedikt05/BetterAltay#24]
so many plugins are using api4 and i want to try it but it seems like it just appears errors

and if i insert plugin that are in api3 it just appears like pmmp/src/pluginloader and __construct or something like that so i didn't know what errors in the plugins that make the plugins disabled

but some plugins not. it's just working as it does

its like inserting your favorite plugins into server folder its just not working

if api4 is trash ok then. but just make me can see the problems on the plugins

**Comment by Benedikt05** [comment]
You can only use Pm3 plugins. Almost every Pm3 plugin will work. If there is any error it will be shown.

**Comment by VaxPex** [comment]
use eskobe it support any api

**Comment by keenanyafiqy** [comment]
no thanks, i found a better software
[click here](https://github.com/ElyNetBE/ElyNetBE) to see the software

**Comment by VaxPex** [comment]
Trash software

**Comment by VaxPex** [comment]
pm4 trash like its creator

**Comment by VaxPex** [comment]
+ if i want to edit pm4 it will be better than this shit

**Comment by VaxPex** [comment]
+ no advertisment

**Comment by VaxPex** [comment]
trash issue like u
