### ISSUE TITLE
Armor Trim Implementation

### ISSUE THREAD

**Issue by DANRULEZ123** [Benedikt05/BetterAltay#243]
## Description
Adds a visual display to armor of any type. (Vanilla Feature)

## Justification
Armor Trim implementation allows for more diversity in terms of armor visual displaying and could be used for a plethora of things.

## Alternative methods
I've attempted to use nbt tags to add it just like it's done in pm5 but to no avail.

**Comment by Benedikt05** [comment]
works for me, here is an example:

	public function onCommand(CommandSender $sender, Command $command, string $label, array $args) : bool{
		if(!$command->getName() == "test"){
			return false;
		}

		if(!$sender instanceof Player){
			return false;
		}

		$item = $sender->getInventory()->getItemInHand();

		if(!$item instanceof Armor){
			$sender->sendMessage("Item must be an armor!");
			return true;
		}

		self::create($item, "amethyst", "coast");
		$sender->getInventory()->setItemInHand($item);
		return true;
	}

	public static function create(Armor $armor, string $material, string $pattern) : void{
		$nbt = $armor->getNamedTag();

		$tag = new CompoundTag("Trim");
		$tag->setString("Material", $material);
		$tag->setString("Pattern", $pattern);
		$nbt->setTag($tag);

		$armor->setNamedTag($nbt);
	}
