### ISSUE TITLE
Update Betteratlay! And make it good 

### ISSUE THREAD

**Issue by Chiragthepiro** [Benedikt05/BetterAltay#257]
So I have skyblock backup of api 3 and I want to join able from api 5 version so I found this betteratlay,  but there are some plugins which are not working,  like /recipebook < these are popular plugins which were discontinued and more such plugin 

I cannot tel, what is wrong but I can tell that
Form api etc stuff 

It's a missing game feature , if betteratlay is for running api 3 plugins on api 5 and let it be good
I dont know good about php but bro still,  there is error and it affect gameplay alot

**Comment by asker1321** [comment]
Instead of putting (): array in formapi, use (): mixed{

**Comment by Benedikt05** [comment]
seems like issues related to plugins, you can ask for help on the discord to fix them
