### ISSUE TITLE
EVENTS?

### ISSUE THREAD

**Issue by AfterKing** [Benedikt05/BetterAltay#268]
### Issue description

- Expected result: cencel event
- Actual result: When I cancel the damage event it still gives the damage, this must be the same inventory error

### Steps to reproduce the issue
1. ...
2. ...

### OS and versions

* Altay:
* PHP:
* Using JIT: yes/no (delete as appropriate) 
* Server OS:
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

    public function onEntityDamage(EntityDamageEvent $event): void {

    $entity = $event->getEntity();
    if (!($entity instanceof Player)) {
         return;
    }
    if ($entity instanceof SlapperEntity || $entity instanceof SlapperHuman) {
        $event->setCancelled(true);
        if (!$event instanceof EntityDamageByEntityEvent) {
            return;
        }
        $damager = $event->getDamager();
        if (!$damager instanceof Player) {
            return;
        }
        $this->getServer()->getPluginManager()->callEvent($event = new SlapperHitEvent($entity, $damager));

        if ($event->isCancelled()) {
             return;
        }

        $damagerName = $damager->getName();

        if (isset($this->hitSessions[$damagerName])) {
             if ($entity instanceof SlapperHuman) {
                 $entity->getInventory()->clearAll();
             }
             $entity->close();
             unset($this->hitSessions[$damagerName]);
             $damager->sendMessage($this->prefix . "Entity removed.");
             return;
        }

        if (isset($this->idSessions[$damagerName])) {
            $damager->sendMessage($this->prefix . "Entity ID: " . $entity->getId());
            unset($this->idSessions[$damagerName]);
            return;
        }
        if (($commands = $entity->namedtag->getCompoundTag("Commands")) !== null) {
            $server = $this->getServer();
            /** @var StringTag $stringTag */
            foreach ($commands as $stringTag) {
                $server->dispatchCommand(new ConsoleCommandSender(), str_replace("{player}", '"' . $damagerName . '"', $stringTag->getValue()));
            }
        }
    }

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by DANRULEZ123** [comment]
I also experienced issues with this. I think it is an issue with $event->isCancelled();

**Comment by AfterKing** [comment]
isCancelled and the other event

**Comment by AfterKing** [comment]
is my plugin, sorry!
