### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by kaio200816** [Benedikt05/BetterAltay#285]
23:30:49 Server|CRITICAL > UnexpectedValueException: "Too many packets in a single batch" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket" at line 139
23:30:49 Server|CRITICAL > #0 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(161): pocketmine\network\mcpe\protocol\BatchPacket->getPackets()
23:30:49 Server|CRITICAL > #1 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(135): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
23:30:49 Server|CRITICAL > #2 pmsrc/src/pocketmine/Player(3793): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
23:30:49 Server|CRITICAL > #3 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(185): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
23:30:49 Server|CRITICAL > #4 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[20] 177.37.182.112 61993, object raklib\protocol\EncapsulatedPacket, integer 0)
23:30:49 Server|CRITICAL > #5 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(116): raklib\server\ServerHandler->handlePacket()
23:30:49 Server|CRITICAL > #6 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(106): pocketmine\network\mcpe\RakLibInterface->process()
23:30:49 Server|CRITICAL > #7 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
23:30:49 Server|CRITICAL > #8 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
23:30:49 Server|CRITICAL > #9 pmsrc/src/pocketmine/Server(2313): pocketmine\snooze\SleeperHandler->sleepUntil(double 1722987049.2525)
23:30:49 Server|CRITICAL > #10 pmsrc/src/pocketmine/Server(2155): pocketmine\Server->tickProcessor()
23:30:49 Server|CRITICAL > #11 pmsrc/src/pocketmine/Server(1730): pocketmine\Server->start()
23:30:49 Server|CRITICAL > #12 pmsrc/src/pocketmine/PocketMine(333): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
23:30:49 Server|CRITICAL > #13 pmsrc/src/pocketmine/PocketMine(363): pocketmine\server()
23:30:49 Server|CRITICAL > #14 pmsrc(11): require(string[69] phar:///home/container/BetterAltay.phar/src/pocketmine/PocketMine.php)
23:30:55 Server|CRITICAL > UnexpectedValueException: "Too many packets in a single batch" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket" at line 139
23:30:55 Server|CRITICAL > #0 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(161): pocketmine\network\mcpe\protocol\BatchPacket->getPackets()
23:30:55 Server|CRITICAL > #1 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(135): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
23:30:55 Server|CRITICAL > #2 pmsrc/src/pocketmine/Player(3793): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
23:30:55 Server|CRITICAL > #3 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(185): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
23:30:55 Server|CRITICAL > #4 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[20] 177.37.182.112 61993, object raklib\protocol\EncapsulatedPacket, integer 0)
23:30:55 Server|CRITICAL > #5 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(116): raklib\server\ServerHandler->handlePacket()
23:30:55 Server|CRITICAL > #6 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(106): pocketmine\network\mcpe\RakLibInterface->process()
23:30:55 Server|CRITICAL > #7 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
23:30:55 Server|CRITICAL > #8 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
23:30:55 Server|CRITICAL > #9 pmsrc/src/pocketmine/Server(2313): pocketmine\snooze\SleeperHandler->sleepUntil(double 1722987054.9525)
23:30:55 Server|CRITICAL > #10 pmsrc/src/pocketmine/Server(2155): pocketmine\Server->tickProcessor()
23:30:55 Server|CRITICAL > #11 pmsrc/src/pocketmine/Server(1730): pocketmine\Server->start()
23:30:55 Server|CRITICAL > #12 pmsrc/src/pocketmine/PocketMine(333): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
23:30:55 Server|CRITICAL > #13 pmsrc/src/pocketmine/PocketMine(363): pocketmine\server()
23:30:55 Server|CRITICAL > #14 pmsrc(11): require(string[69] phar:///home/container/BetterAltay.phar/src/pocketmine/PocketMine.php)
23:31:00 Server|CRITICAL > UnexpectedValueException: "Too many packets in a single batch" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket" at line 139
23:31:00 Server|CRITICAL > #0 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(161): pocketmine\network\mcpe\protocol\BatchPacket->getPackets()
23:31:00 Server|CRITICAL > #1 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(135): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
23:31:00 Server|CRITICAL > #2 pmsrc/src/pocketmine/Player(3793): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
23:31:00 Server|CRITICAL > #3 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(185): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
23:31:00 Server|CRITICAL > #4 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[20] 177.37.182.112 61993, object raklib\protocol\EncapsulatedPacket, integer 0)
23:31:00 Server|CRITICAL > #5 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(116): raklib\server\ServerHandler->handlePacket()
23:31:00 Server|CRITICAL > #6 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(106): pocketmine\network\mcpe\RakLibInterface->process()
23:31:00 Server|CRITICAL > #7 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
23:31:00 Server|CRITICAL > #8 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
23:31:00 Server|CRITICAL > #9 pmsrc/src/pocketmine/Server(2313): pocketmine\snooze\SleeperHandler->sleepUntil(double 1722987060.6024)
23:31:00 Server|CRITICAL > #10 pmsrc/src/pocketmine/Server(2155): pocketmine\Server->tickProcessor()
23:31:00 Server|CRITICAL > #11 pmsrc/src/pocketmine/Server(1730): pocketmine\Server->start()
23:31:00 Server|CRITICAL > #12 pmsrc/src/pocketmine/PocketMine(333): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
23:31:00 Server|CRITICAL > #13 pmsrc/src/pocketmine/PocketMine(363): pocketmine\server()
23:31:00 Server|CRITICAL > #14 pmsrc(11): require(string[69] phar:///home/container/BetterAltay.phar/src/pocketmine/PocketMine.php)
23:31:07 Server|CRITICAL > UnexpectedValueException: "Too many packets in a single batch" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket" at line 139
23:31:07 Server|CRITICAL > #0 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(161): pocketmine\network\mcpe\protocol\BatchPacket->getPackets()
23:31:07 Server|CRITICAL > #1 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(135): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
23:31:07 Server|CRITICAL > #2 pmsrc/src/pocketmine/Player(3793): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
23:31:07 Server|CRITICAL > #3 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(185): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
23:31:07 Server|CRITICAL > #4 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[20] 177.37.182.112 61993, object raklib\protocol\EncapsulatedPacket, integer 0)
23:31:07 Server|CRITICAL > #5 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(116): raklib\server\ServerHandler->handlePacket()
23:31:07 Server|CRITICAL > #6 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(106): pocketmine\network\mcpe\RakLibInterface->process()
23:31:07 Server|CRITICAL > #7 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
23:31:07 Server|CRITICAL > #8 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
23:31:07 Server|CRITICAL > #9 pmsrc/src/pocketmine/Server(2313): pocketmine\snooze\SleeperHandler->sleepUntil(double 1722987067.6024)
23:31:07 Server|CRITICAL > #10 pmsrc/src/pocketmine/Server(2155): pocketmine\Server->tickProcessor()
23:31:07 Server|CRITICAL > #11 pmsrc/src/pocketmine/Server(1730): pocketmine\Server->start()
23:31:07 Server|CRITICAL > #12 pmsrc/src/pocketmine/PocketMine(333): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
23:31:07 Server|CRITICAL > #13 pmsrc/src/pocketmine/PocketMine(363): pocketmine\server()
23:31:07 Server|CRITICAL > #14 pmsrc(11): require(string[69] phar:///home/container/BetterAltay.phar/src/pocketmine/PocketMine.php)

**Comment by Benedikt05** [comment]
Dublicate of #284
