### ISSUE TITLE
nether is bug 

### ISSUE THREAD

**Issue by AfterKing** [Benedikt05/BetterAltay#295]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. ...
2. ...

### OS and versions

* Altay:
* PHP:
* Using JIT: yes/no (delete as appropriate) 
* Server OS:
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by AfterKing** [comment]
![image](https://github.com/user-attachments/assets/f54833de-51b2-44e9-ab54-d9be84bab740)

**Comment by AfterKing** [comment]
to customize the buttons on mobile it is also like this

**Comment by Benedikt05** [comment]
does the issue still occur without any plugins?

**Comment by Benedikt05** [comment]
> to customize the buttons on mobile it is also like this

provide some more details please

**Comment by AfterKing** [comment]
When you teleport to the nether you get the error: "invalid package"

**Comment by Benedikt05** [comment]
try it without plugins
