### ISSUE TITLE
working portals plz?

### ISSUE THREAD

**Issue by efor89** [Benedikt05/BetterAltay#39]
hi
can you implement working portals for end and nether plz?

**Comment by Benedikt05** [comment]
I can't at the moment because I don't have much time. Maybe in a few months.

**Comment by efor89** [comment]
ok np its only a nice to have

**Comment by VaxPex** [comment]
esko had them

**Comment by efor89** [comment]
wat is esko?

**Comment by VaxPex** [comment]
look at the forks
