### ISSUE TITLE
andesit deorit granit craftingtable bug

### ISSUE THREAD

**Issue by efor89** [Benedikt05/BetterAltay#40]
hi 
i become in the crafting table endstoneslap with andesit deorit or granit blocks

### Steps to reproduce the issue
1. open crafting table
2. put andesit in crafting table

### OS and versions

* Altay: 3.28.0
* PHP: 8
* Using JIT: no
* Server OS: 
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins
clean server without plugins

![Screenshot (36)](https://user-images.githubusercontent.com/67799203/156215935-d163a312-170c-4d0c-9912-a5c920023f6c.png)
![Screenshot (37)](https://user-images.githubusercontent.com/67799203/156215958-f654cf36-ebb6-4cd5-ad47-b7dbc1517840.png)

**Comment by Benedikt05** [comment]
I don't have this issue

**Comment by efor89** [comment]
mhh i use the nether, end hackfix version.

**Comment by efor89** [comment]
i have a question why is the sponsor link for pmmp and not for you?

**Comment by Benedikt05** [comment]
> i have a question why is the sponsor link for pmmp and not for you?

I don't have one. If you want to donate, donate to Pocketmine.

**Comment by Benedikt05** [comment]
> mhh i use the nether, end hackfix version.

I tried it with that

**Comment by efor89** [comment]
then idn why i remove all plugins for the test and i can craft the slaps with a d g.

**Comment by Benedikt05** [comment]
> then idn why i remove all plugins for the test and i can craft the slaps with a d g.

Idk
