### ISSUE TITLE
some particle not working

### ISSUE THREAD

**Issue by efor89** [Benedikt05/BetterAltay#49]
### Issue description

Hi i try to use Particle for myplot but some particle not working.
angryvillager, happyvillager, splash, bubble, flame, heart, watterdrip, lavadrip, spore, explode, smoke

### OS and versions

* Altay: 3.28.0
* PHP: 8
* Using JIT: no
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins

* myplot
* formapi
* plotparticle

### Pictures

the angryvillager and happyvillagerparticle not working
![Screenshot (54)](https://user-images.githubusercontent.com/67799203/160374169-f69ef640-69aa-45d3-ad36-1400291dda01.png)
![Screenshot (55)](https://user-images.githubusercontent.com/67799203/160374252-5883af09-8187-4c9f-872c-12a89ec615ac.png)

the entityflameparticle working
![Screenshot (56)](https://user-images.githubusercontent.com/67799203/160374272-bdc8c75f-5bd8-4a09-913b-0d415671b0ac.png)

**Comment by PocketMiner92** [comment]
Altay?
This stupid Shit exist anymore?
You should Change to another Software.
Altay is a Peace of Shit.

**Comment by efor89** [comment]
@PocketMiner92 
pmmp 4 is not better its like update win 10 to win 11 ;)
in the moment it is best to use win 10 and dont update to 11.

in the moment is best to use altay and not update to api4

**Comment by Benedikt05** [comment]
Is it the same in Pm3?

**Comment by PocketMiner92** [comment]
Or use Powernukkit or Nukkit PetteriM1 Edition.

**Comment by efor89** [comment]
> Is it the same in Pm3?

i dont know pm3 is no longer existing.

**Comment by N0Name1015** [comment]
> > Is it the same in Pm3?
> 
> i dont know pm3 is no longer existing.

It does? It's even still the latest version.

**Comment by Benedikt05** [comment]
> > Is it the same in Pm3?
> 
> i dont know pm3 is no longer existing.

You can still download the phar and it still works for the latest version of Minecraft.

**Comment by efor89** [comment]
yes its the same in pm3

**Comment by VaxPex** [comment]
:(
