### ISSUE TITLE
German Language not working

### ISSUE THREAD

**Issue by efor89** [Benedikt05/BetterAltay#51]
### Issue description

hi 
if i use deu as lang the server give me this info at start.
07:05:44 Server|INFO > Selected English (deu) as the base language
i hope you can fix it that i can use german lang plz.

### Steps to reproduce the issue
1. deu in settings
2. start server

### OS and versions
* Altay: 3.28.0
* PHP: 8
* Using JIT: no
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

**Comment by Benedikt05** [comment]
If you build the phar yourself, it will work (master branch)

**Comment by efor89** [comment]
idn how i build a server.phar i try it a lot of time but was always not working -.-

**Comment by PocketMiner92** [comment]
Use this
https://github.com/MCPE357/EskoBE

**Comment by efor89** [comment]
> Use this https://github.com/MCPE357/EskoBE

i use EskoBE and BetterAltay
but in this 2 the german lang is not working and idk how tu build a server.phar

**Comment by Benedikt05** [comment]
Yeah, it will work in the next release.

**Comment by efor89** [comment]
thx 👍
