### ISSUE TITLE
problem with floatingtextparticle plugins

### ISSUE THREAD

**Issue by efor89** [Benedikt05/BetterAltay#58]
### Issue description

hi have the problem that all plugins wat use floatingtextpartikel not longer working.
some time i join and cant walk and 2-4 sec later i autmatic leave the server.
but most time i try to join and i leave before i ingame.
sry for my bad english :P

### Steps to reproduce the issue
1. install plugin with floatingtextparticle (moneyleaderbord or onlinetime leaderboard or some thing else)
2. spawn the floatingtextparticle
3. start server
4. join server

### OS and versions

* Altay: betteraltay 3.28.0 for version 1.18.30
* PHP: 8
* Using JIT: no
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins
* moneyleaderboard
* onlinetimeleaderboard
* clanleaderboard
* topvoterleaderbord
* mysterycrate
* floatingtextcreator

### Crashdump, backtrace or other files
no crash
16:02:35 Server|INFO > efor89[/79.251.81.89:62154] loggte sich mit Entity ID 4 bei (popup, 52.649, 65, 52.0984) ein
16:02:39 Server|INFO > efor89[/79.251.81.89:62154] loggte sich wegen "client disconnect" aus

**Comment by VaxPex** [comment]
Fixed but not released the fixed ver

**Comment by efor89** [comment]
working thx
