### ISSUE TITLE
PlayerFischEvent

### ISSUE THREAD

**Issue by efor89** [Benedikt05/BetterAltay#68]
## Description
hi i try to setCustomName() and setLore() in PlayerFishEvent() but i cant.
also i try to set other items wat i can catch with fishing.
so my question can you add getItem() and setItem() in PlayerFishEvent() plz? 

## Justification
its easy to make custom fishsystem, add new items with setItem() like boots, clock or deathbush.
also its easy to setCustomName() or setLore([]) with getItem().

## Alternative methods
in the moment i give the fish with InventoryPickupItemEvent customname and lore but i need a lot if() in it and its not the best way.

**Comment by JoseLuisHD** [comment]
Scheduled for 1.19.40 after testing
