### ISSUE TITLE
Always Disconnect with Waterdog

### ISSUE THREAD

**Issue by FoxyCodeX** [Benedikt05/BetterAltay#69]
When I was playing with WaterdogPE Proxy, I suddenly disconnected. I was able to join, but after a while it disconnected. Can you fix it?

**Comment by Benedikt05** [comment]
I will fix it. Use 1.1.1 release until it's fixed.

**Comment by FoxyCodeX** [comment]
v1.1.1 is still error. I will waiting for new updates

**Comment by efor89** [comment]
> v1.1.1 is still error. I will waiting for new updates

only end and nether are not working for me in the 1.1.1 . waterdogpe works for me

**Comment by VaxPex** [comment]
wtf with u pll

**Comment by Benedikt05** [comment]
It should be fixed in the latest releases
